### ISSUE TITLE
[BUG]: Workspace cannot upload files named in Mandarin (pre-release build in comments)

### ISSUE THREAD

**Issue by solocugb** [Mintplex-Labs/anything-llm#1881] opened 2024-07-17 08:12 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

when i upload  a file to workspace ,it's  always loading! i can not upload  any files.  my os is mac os !
![WX20240717-161120@2x](https://github.com/user-attachments/assets/47bac023-fdd8-4796-a823-a5b34517bfe7)

**Comment by solocugb** [comment] 2024-07-17 08:14
i forgot to tell that the version of anythingLLM  i am using is v1.5.9

**Comment by Cleverqiu07** [comment] 2024-07-17 08:38
Same things happened on both my Mac and Widnows computer, the version I am using is 1.5.10.

**Comment by YuangFeng** [comment] 2024-07-17 10:03
Same

**Comment by hejp001** [comment] 2024-07-17 14:52
> Same things happened on both my Mac and Windows computer, the version I am using is 1.5.9 or 1.5.10.

**Comment by timothycarambat** [comment] 2024-07-17 15:54
Can you rename you files to have latin characters and upload the file again? I belive this issue is related to the file chars being non-utf8

**Comment by ayaka209** [comment] 2024-07-17 21:32
Renaming files to Latin characters isn't practical; we have so many documents. Files with English names can be uploaded successfully.

**Comment by timothycarambat** [comment] 2024-07-18 01:32
@ayaka209 Yeah, that is why I asked, I wanted to confirm that was the reproducible issue so I could narrow it down. It will be patched - just wanted to confirm. Until the patch is released that is the workaround, will get the patch out soon once we find the root cause.

**Comment by timothycarambat** [comment] 2024-07-18 01:32
When this issue is closed, the patch is out

**Comment by solocugb** [comment] 2024-07-18 01:59
> Can you rename you files to have latin characters and upload the file again? I belive this issue is related to the file chars being non-utf8

okay,let me try

**Comment by solocugb** [comment] 2024-07-18 02:03
> Can you rename you files to have latin characters and upload the file again? I belive this issue is related to the file chars being non-utf8

it worked for me ,thx

**Comment by hejp001** [comment] 2024-07-18 02:04
Renaming the file name to English or Arabic numerals still cannot be uploaded.
![屏幕截图 2024-07-18 100153](https://github.com/user-attachments/assets/62ac84a5-a8c9-414c-9888-42fe9a224434)

**Comment by hejp001** [comment] 2024-07-18 02:08
> Renaming the file name to English or Arabic numerals still cannot be uploaded. ![屏幕截图 2024-07-18 100153](https://private-user-images.githubusercontent.com/62975933/349755929-62ac84a5-a8c9-414c-9888-42fe9a224434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjg1NjIsIm5iZiI6MTcyMTI2ODI2MiwicGF0aCI6Ii82Mjk3NTkzMy8zNDk3NTU5MjktNjJhYzg0YTUtYThjOS00MTRjLTk4ODgtNDJmZTlhMjI0NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAyMDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2E1Y2Y4M2QzZTU1ZmYzMDVmNGI2YTg0ZGJiNGNlNTc3YzIxMjAxNDNkZTZiZjJjMTFhNGJjM2JmNGIyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FIj3ZYu6g63GISzV24JGH5Fb8Y6VmxHyR0_FxYR3_CM)

Version 1.5.8.0 doesn't have this problem. I'm using the Windows desktop version.

**Comment by hejp001** [comment] 2024-07-18 02:09
Version 1.5.8.0 doesn't have this problem. I'm using the Windows desktop version.

**Comment by timothycarambat** [comment] 2024-07-18 03:05
Windows Staging Download Link (pre-release): https://s3.us-west-1.amazonaws.com/public.useanything.com/staging/AnythingLLMDesktop.exe

Apple Intel: https://s3.us-west-1.amazonaws.com/public.useanything.com/staging/AnythingLLMDesktop.dmg

**Comment by solocugb** [comment] 2024-07-18 03:06
> e uploaded.

do u try to restart ur os,then try again

**Comment by hejp001** [comment] 2024-07-18 03:41
The problem has been solved. Thank you!

**Comment by timothycarambat** [comment] 2024-07-18 04:16
Once we get the silicon build deployed we can push this new version. Locking the thread for now since its confirmed patched. When thread is closed 1.5.11 is live.

**Comment by timothycarambat** [comment] 2024-07-18 04:30
1.5.11 is live now
resolved by 2425d18abd6a5c5e7496ef198bc6c34fa1f8889b

**Closed by timothycarambat** 2024-07-18 04:30 UTC
Labels: core-team-only, Desktop, investigating
