### ISSUE TITLE
[FEAT]: Support more than one of the same type LLM Provider

### ISSUE THREAD

**Issue by djstrong** [Mintplex-Labs/anything-llm#1967] opened 2024-07-25 15:23 UTC
### What would you like to see?

Support more than one of the same type LLM Provider, e.g. Local AI or Generic OpenAI.

I have many "Local AI" providers but only one can be configured.

**Comment by timothycarambat** [comment] 2024-07-25 17:15
This is a duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/1567 - same concept and idea. That issue is what we refer to this as so if when issue is closed then this request exists in the app

**Closed by timothycarambat** 2024-07-25 17:15 UTC
Labels: enhancement, feature request
