### ISSUE TITLE
[BUG]: loading available models between two win11 pcs

### ISSUE THREAD

**Issue by Wikibear** [Mintplex-Labs/anything-llm#1910] opened 2024-07-20 14:26 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Ollama is reachable via website and curl from client to Ollama host.
If i try to connect with AnythingLLM I get only the message --loading available models--
Nothing else happens. AnythingLLM on host system works, but not on client.
Try to figure out why:
Get **no** message nor any request via Powershell on host machine from client side AnythingLLM
I checked Windows 11 firewall but entry is correct. Can't find any issues here.
Try to start AnythingLLM as Administrator with no success.
No bad logs are available.
Netstat doesn't show any activity's to port 11434 via netstat -ob

For me it's look like no request is outgoing if the IP isn't the local one.

Version 1.5.11 is in use.

**Comment by timothycarambat** [comment] 2024-07-20 17:34
For clarification:
- You have one PC running Ollama using their windows application, this is not in Docker or WSL, correct?
- You have another PC running AnythingLLM, presumably on the same LAN
- Each PC can run their respective programs on their host machines, no issue.

You are using the private IP of the Ollama on PC1 in the AnythingLLM app on PC2 and PC2 is saying it cannot connect.

I am going to close the issue because this is not a bug, it's a configuration issue from your setup almost certainly, however, we can continue to chat in this thread to debug. If the above situation is what is occurring and you know the firewall perms are correct then there are two ways of debugging this:

1. Make sure you are binding to the right host on Ollama machine. By default ollama binds to 127.0.0.1 and not 0.0.0.0
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

2. Just use `ngrok` and run `ngrok HTTP 11434` copy the generated URL and paste that into AnythingLLM. Its a tunnel so its not fully LAN, but that would be a way to validate that at least each system is running respectively.

**Closed by timothycarambat** 2024-07-20 17:34 UTC
Labels: possible bug

**Comment by Wikibear** [comment] 2024-07-20 19:05
Thanks for your support.
No Docker nor WSL. I have a host in the same LAN. My Client is a Laptop and don't have enough power. So have one PC with 
Windows 11 as a host and another Windows 11 as a client, that's my Laptop. Ollama is working fine on Host also on the same machine via 127.0.0.1 with AnythingLLM. I made sure that the host is running without any issue. So then I start with client and found out that Ollama need special binding command I do it and checked with curl that the host is reachable. And then the debugging starts:

I can reach Ollama thru powershell from my client as I wrote this before:
![grafik](https://github.com/user-attachments/assets/ae119212-407d-4b45-a820-2b820900e175)
Website show this:
![grafik](https://github.com/user-attachments/assets/b18864bd-bb74-423a-b4bb-17b7b47200ad)
So just start a query with curl form the client to the host:
![grafik](https://github.com/user-attachments/assets/703f2863-b8d6-4d29-a45a-a816ca8f5fa9)
It's also working. OK let's try another client. A Raspi. Let's check:
![grafik](https://github.com/user-attachments/assets/032672a0-27b9-40bc-be37-313c02afd93a)
Oh, nice it's working also with my Raspi.
Check with Wireshark on my client Windows 11 PC and make a request to my host with curl:
![grafik](https://github.com/user-attachments/assets/2e710c15-7f20-45d9-9269-0541bf4cf574)
Nice that's working as aspected.
So I remove AnythingLLM from my client system, delete everything and make a fresh new install. The installation is awesome... slow.
After new installation, I get get started screen. Set Ollama and ip with port aaaaaaaaaaaaaaand that's working without any problem. 
I don't understand this why it's working now. There must be a configuration error or something like that. I tried before without special settings for the binding on host machine. So I got it never to work as aspected. Dunno think everything looks good now.
