### ISSUE TITLE
[BUG]: Desktop app error on creating new workspace

### ISSUE THREAD

**Issue by jaschadub** [Mintplex-Labs/anything-llm#1184] opened 2024-04-24 22:59 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Started AppImage and tried to create workspace got attached error.
![Screenshot_2024-04-24_15-56-33](https://github.com/Mintplex-Labs/anything-llm/assets/768841/e9416623-6dc8-4416-bf30-853f33845de3)

### Are there known steps to reproduce?

Download desktop app v1.5.0 for Linux on Xbuntu and try to create a workspace.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

**Comment by timothycarambat** [comment] 2024-04-24 23:08
duplicate of #898

Move convo to that thread


@jaschadub Can you attempt to use this staging version of AnythingLLM AppImage
https://github.com/Mintplex-Labs/anything-llm/issues/898#issuecomment-2067412115

**Closed by timothycarambat** 2024-04-24 23:08 UTC
Labels: possible bug
