### ISSUE TITLE
[BUG]: fail to start with win10

### ISSUE THREAD

**Issue by griswold911** [Mintplex-Labs/anything-llm#2361] opened 2024-09-24 09:34 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

use cmd to start anythingllm.exe and stop as follow
C:\Program Files\AnythingLLM>
[Preferences] preference config stored at C:\Users\Administrator\AppData\Roaming\anythingllm-desktop\config.json

install for all,windows 10 os and CPU amd 4800H

**Comment by timothycarambat** [comment] 2024-09-24 21:26
Anything more to that log? There is no actionable information in that log. It just hangs? Closing until a root cause is discovered

**Closed by timothycarambat** 2024-09-24 21:26 UTC
Labels: possible bug

**Comment by griswold911** [comment] 2024-09-25 00:48
more log here today，just hangs here

C:\Program Files\AnythingLLM>AnythingLLM.exe

C:\Program Files\AnythingLLM>
[Preferences] preference config stored at C:\Users\Administrator\AppData\Roaming\anythingllm-desktop\config.json
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:C:/Users/Administrator/AppData/Roaming/anythingllm-desktop/storage/anythingllm.db"

Already in sync, no schema change or pending migration was found.

Running generate... (Use --skip-generate to skip the generators)
