### ISSUE TITLE
[FEAT]: Data Connectors Git

### ISSUE THREAD

**Issue by Minecodes** [Mintplex-Labs/anything-llm#1160] opened 2024-04-21 09:22 UTC
### What would you like to see?

I would like a data connector for Git, not just GitHub because I have a private Git instance that I can't connect as a data source. That meant I had to mirror every repository I wanted to add.

**Comment by timothycarambat** [comment] 2024-04-21 18:50
Duplicate of #923 - will be tracked there

**Closed by timothycarambat** 2024-04-21 18:50 UTC
Labels: duplicate, enhancement, feature request
