### ISSUE TITLE
[FEAT]:  Add API Key support to the initial configuration options during deployment, and possibly add it to the API

### ISSUE THREAD

**Issue by ajferrario** [Mintplex-Labs/anything-llm#1869] opened 2024-07-15 06:43 UTC
### What would you like to see?

As an anythingllm administrator attempting to deploy a number of anythingllm environments, I currently need to create an API Key for the initial Admin user in each environment manually before I can use the API to configure the needed users, workspaces and other features for that environment.

I'd like to have a fully-automated and hands-off deployment option, and this is one of the main manual steps blocking me from achieving this.

Adding it to the API would be for enabling other users to use anythingllm without ever having to use the GUI.

I will file other issues for a couple other things needed for fully-automated deployments.

**Comment by timothycarambat** [comment] 2024-07-15 16:20
Duplicate of #1870

**Closed by timothycarambat** 2024-07-15 16:20 UTC
Labels: enhancement, feature request
