### ISSUE TITLE
[BUG]: the implementation of the answer in the web interface is very annoying - during the answer the window constantly scrolls down and twitches.

### ISSUE THREAD

**Issue by iqs-systems** [Mintplex-Labs/anything-llm#2340] opened 2024-09-21 06:08 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

the implementation of the answer in the web interface is very annoying - during the answer the window constantly scrolls down and twitches. it is very inconvenient to read during the answer. with long answers you have to wait for the end of the answer and only then read

### Are there known steps to reproduce?

in every long answer in web interfaces

**Comment by iqs-systems** [comment] 2024-09-21 06:10
scrolling up while answering doesn't help at all

**Comment by timothycarambat** [comment] 2024-09-21 21:19
Duplicate of #2253, which as a PR right now

**Closed by timothycarambat** 2024-09-21 21:19 UTC
Labels: possible bug
