### ISSUE TITLE
[BUG]: failed to load the native whisper model

### ISSUE THREAD

**Issue by help4bis** [Mintplex-Labs/anything-llm#1157] opened 2024-04-21 04:29 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

Uploading a large mp4 file to a "virgin" installation creates the following error. 

Part of .env file
LLM_PROVIDER='ollama'
OPEN_AI_KEY='sk-xxxxxxxxxxxxxxx'
EMBEDDING_MODEL_PREF='wizardlm2:latest'
OLLAMA_BASE_PATH='http://xxxxxx7:11434'
OLLAMA_MODEL_PREF='wizardlm2:latest'
OLLAMA_MODEL_TOKEN_LIMIT='2048'
EMBEDDING_ENGINE='native'
EMBEDDING_BASE_PATH='http://xxxxxxxx7:11434'
EMBEDDING_MODEL_MAX_CHUNK_LENGTH='6144'
VECTOR_DB='lancedb'

Error:
[wisperError.txt](https://github.com/Mintplex-Labs/anything-llm/files/15050657/wisperError.txt)

[LocalWhisper] Failed to load the native whisper model: Error: Unsupported model type: whisper
    at AutoModelForCTC.from_pretrained (file:///app/collector/node_modules/@xenova/transformers/src/models.js:4667:19)
    at async file:///app/collector/node_modules/@xenova/transformers/src/pipelines.js:2677:33
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Unsupported model type: whisper
    at AutoModelForCTC.from_pretrained (file:///app/collector/node_modules/@xenova/transformers/src/models.js:4667:19)
    at async file:///app/collector/node_modules/@xenova/transformers/src/pipelines.js:2677:33

Node.js v18.19.1

### Are there known steps to reproduce?

Scenario:
1. uploading large MP4 about 300mb
2. Native whisper model has not run before.

**Comment by timothycarambat** [comment] 2024-04-21 18:49
Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/539
Related library convo: https://github.com/xenova/transformers.js/issues/314

If running on docker are you building the image for the proper processor arch that the OS is running? That was the root cause last time. Docker was running the model in an emulated x86 environment and it was incompatible running on an ARM chip

**Closed** 2024-04-30 23:00 UTC
Labels: needs info / can't replicate
