### ISSUE TITLE
[BUG]: Install on Ubuntu 22.04 fails

### ISSUE THREAD

**Issue by geraldthewes** [Mintplex-Labs/anything-llm#1405] opened 2024-05-15 11:14 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Downloaded and launched. Unable to create a Workspace

(base) gerald@gerald-XPS-15-9570 Software $ ./AnythingLLMDesktop.AppImage 
[Preferences] preference config stored at /home/gerald/.config/anythingllm-desktop/config.json
[292910:0515/063359.348562:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/gerald/.config/anythingllm-desktop/storage/anythingllm.db"

Error: Schema engine exited. Error: Could not find schema-engine binary. Searched in:
- /tmp/.mount_Anythi9eDIIq/resources/backend/node_modules/@prisma/engines/schema-engine-debian-openssl-1.0.x
- /tmp/.mount_Anythi9eDIIq/resources/backend/node_modules/prisma/schema-engine-debian-openssl-1.0.x
- /tmp/.mount_Anythi9eDIIq/resources/backend/node_modules/schema-engine-debian-openssl-1.0.x
- /tmp/.mount_Anythi9eDIIq/resources/backend/node_modules/prisma/runtime/schema-engine-debian-openssl-1.0.x
Prisma schema loaded from prisma/schema.prisma
Error: 
EROFS: read-only file system, unlink '/tmp/.mount_Anythi9eDIIq/resources/backend/node_modules/.prisma/client/index.js'

[OllamaProcessManager] Ollama will bind on port 11434 when booted.
[OllamaProcessManager] Creating Ollama models folder in application storage. {
  destination: '/home/gerald/.config/anythingllm-desktop/storage/models/ollama'
}
[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.
[OllamaProcessManager] Cannot boot Ollama - no executable found in /tmp/.mount_Anythi9eDIIq/resources/ollama/llm
[292946:0515/064117.918078:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[292946:0515/064120.973706:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[292946:0515/064153.320107:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
^C[Preferences] Saving last_bounds preference.
(base) gerald@gerald-XPS-15-9570 Software $ ./AnythingLLMDesktop.AppImage 
[Preferences] preference config stored at /home/gerald/.config/anythingllm-desktop/config.json
[333229:0515/070141.825322:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/gerald/.config/anythingllm-desktop/storage/anythingllm.db"

Error: Schema engine exited. Error: Could not find schema-engine binary. Searched in:
- /tmp/.mount_Anythitzlfl0/resources/backend/node_modules/@prisma/engines/schema-engine-debian-openssl-1.0.x
- /tmp/.mount_Anythitzlfl0/resources/backend/node_modules/prisma/schema-engine-debian-openssl-1.0.x
- /tmp/.mount_Anythitzlfl0/resources/backend/node_modules/schema-engine-debian-openssl-1.0.x
- /tmp/.mount_Anythitzlfl0/resources/backend/node_modules/prisma/runtime/schema-engine-debian-openssl-1.0.x
Prisma schema loaded from prisma/schema.prisma
Error: 
EROFS: read-only file system, unlink '/tmp/.mount_Anythitzlfl0/resources/backend/node_modules/.prisma/client/index.js'

[OllamaProcessManager] Ollama will bind on port 11434 when booted.
[Preferences] Will load window with last know bounds.
[333264:0515/070151.168900:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[333264:0515/070151.174689:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[333264:0515/070153.755698:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

### Are there known steps to reproduce?

Download
chmod +x
Run
fails when creating new Workspace

**Comment by timothycarambat** [comment] 2024-05-15 20:26
Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/898

**Closed by timothycarambat** 2024-05-15 20:26 UTC
Labels: possible bug
