### ISSUE TITLE
[Question] Why is the search result quality of anythingllm in development mode much less than that of AnythingLLM Desktop?

### ISSUE THREAD

**Issue by fengnex** [Mintplex-Labs/anything-llm#2525] opened 2024-10-23 09:41 UTC
Ollama, the same local LLM `llama3.1:latest`, lancedb and `nomic-embed-text:latest` are used under the two environments as described in the above title, then save the same pdf and docx documents and search the same question against both anythingllms, but the quality of the answers given by the two is completely different：
The answers provided by the desktop version are generally comprehensive in content, formal in format, and high-end. However, the same questions are not even answered in development mode, or the answers are very brief, and often lack some important content, usually without much format!

What are the reasons for this huge difference? How to ensure that the version compiled by oneself in development mode can also achieve the same or similar query quality as the desktop version? Can anyone please explain these?

**Comment by timothycarambat** [comment] 2024-10-24 22:18
My intuitive reaction is that this is ultimately the difference from the inherent difference between runs of the same models. However, there is one major detail missing that matters.

Are you running the desktop local LLM using an _external_ Ollama and using that _same_ external Ollama for development mode as well? There is very well a way to get the exact message array passed to the Ollama instance. Otherwise, this could be differences between any number of things. I can assure you the code, logic, and ultimately the messages passed to the model should be _the exact same_ which puts the root cause outside of the software and onto the inferencing process.

Interesting question, looking forward to seeing what is going on here - closing but please continue the conversation with more information.

**Closed by timothycarambat** 2024-10-24 22:18 UTC
