### ISSUE TITLE
Number of vectors 

### ISSUE THREAD

**Issue by loki-sh** [Mintplex-Labs/anything-llm#537] opened 2024-01-05 07:58 UTC
I was loading documents into a new workspace and noticed when I shifted from the "Documents" tab to the "Settings" tab the value for "Number of Vectors" was zero. Exiting the settings dialog and going back in and going into the "Settings" tab triggered the value to be updated. What I suspect is happening is the value for the number of vectors is retrieved when the workspace settings dialog is opened but not refreshed when moving from the "Documents" tab to the "Settings" tab.

To recreate:

Create a new workspace.
Go into the workspace settings dialog for the newly created workspace.
Upload some documents and embed them into the new workspace.
As soon as the embedding is completed, go into the "Settings" tab and look at the "Number of Vectors", it will be zero.
Click the "x" to exit the workspace settings dialog.
Go back into the workspace settings dialog.
Click on the "Settings" tab and the "Number of Vectors" will now reflect the number of vectors in the database

**Comment by timothycarambat** [comment] 2024-01-05 17:43
Duplicate of #516 - moving to that issue

**Closed by timothycarambat** 2024-01-05 17:43 UTC
Labels: bug, UI/UX
