### ISSUE TITLE
[FEAT]: Creating build for desktop without using docker

### ISSUE THREAD

**Issue by aslyheer** [Mintplex-Labs/anything-llm#1801] opened 2024-07-02 12:55 UTC
### What would you like to see?

I want to create build files for both Windows and Mac, such as .exe for Windows and .dmg for Mac, from my local environment.

**Comment by timothycarambat** [comment] 2024-07-02 16:35
We will not be supporting this for the foreseeable future - we have plenty to debug on a daily basis from bad Docker configs that opening ourselves up to helping people debug with Electron is going to be out of scope. There are a million "gotchas" in that environment that you are welcome to take upon yourself, but it wont be something we will publish instructions on or explicitly support

**Closed by timothycarambat** 2024-07-02 16:35 UTC
Labels: enhancement, feature request

**Comment by ben-xD** [comment] 2024-07-21 20:47
Could you clarify? I downloaded a dmg to install AnythingLLM for mac, which is an electronJS app. So it must be supported? It looks like that code is just not made available in the repo (hidden) rather than "not supported"? I couldn't find the electronJS or Xcode related code?

**Comment by rc-zb** [comment] 2025-05-16 05:34
Also for GNU/Linux. The authors only provide the built binaries for the latest version. They are neither auditable nor reproducible, and not even universal, as they just can't run in, say, NixOS.
