### ISSUE TITLE
[BUG]: OpenSSL error on .appimage creating workspace on Red Hat Silverblue 40

### ISSUE THREAD

**Issue by gdeyoung** [Mintplex-Labs/anything-llm#1393] opened 2024-05-14 05:02 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I get this error when trying to create a workspace after starting .appimage on Red Hat Silverblue 40.  The .appimage is installed in a folder called applications in my home directory.

Error: Invalid `prisma.workspaces.create()` invocation: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x". This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "rhel-openssl-3.0.x". Add "rhel-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it: generator client { provider = "prisma-client-js" binaryTargets = ["native", "rhel-openssl-3.0.x"] } The following locations have been searched: /tmp/.mount_gearleL2KDHG/resources/backend/node_modules/.prisma/client /tmp/.mount_gearleL2KDHG/resources/backend/node_modules/@prisma/client /home/tim/Documents/anything-llm-desktop/anything-llm/server/node_modules/@prisma/client /tmp/prisma-engines /tmp/.mount_gearleL2KDHG/resources/backend/prisma

### Are there known steps to reproduce?

This is repeatable every time

**Comment by timothycarambat** [comment] 2024-05-14 06:08
Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/898

**Closed by timothycarambat** 2024-05-14 06:08 UTC
Labels: possible bug
