### ISSUE TITLE
[BUG]: fetching website with 4 letters extension

### ISSUE THREAD

**Issue by Kofangun** [Mintplex-Labs/anything-llm#963] opened 2024-03-23 22:44 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

error when i try to fetch website with 4 letters extension like .tech

**Comment by timothycarambat** [comment] 2024-03-25 17:26
You can fetch any website that is available as its just about DNS resolution. There is no limitation for the TLD used. What is more likely is the website is blocking the scraper for any number of reasons. Some websites dont allow any kind of autonomous loading tools, like puppeteer - which we use.

Closing as wontfix for now. If you have any test websites you can post here I'm happy to debug or test on my end but that is likely the issue's root cause.

**Closed by timothycarambat** 2024-03-25 17:26 UTC
Labels: possible bug

**Comment by Kofangun** [comment] 2024-04-02 15:49
would you try https://komasterai.tech ?

**Comment by timothycarambat** [comment] 2024-04-02 16:03
Worked for me, was able to get website text
