### ISSUE TITLE
[BUG]: Can’t import a folder of docs containing other folders. 

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1366] opened 2024-05-12 02:53 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

Can’t upload a whole folder of documents. The folder contains other folders that contain documents. 

For some reason, the file selector won’t let me select a whole folder either. Can only seem to upload single documents, or multiple single documents. 

Also having a problem with drag and drop. Nothing happens. Nothing happens when dropping folders or files. It just doesn’t work. 

Importing a whole folder at once is kind of crucial for usability. 

It’d also be nice to be able to REPLACE documents easily. That also makes it easy to use. If it makes the user feel LESS FRAGMENTED, then it is providing value.

### Are there known steps to reproduce?

On Ubuntu. 

Click open and nothing happens. 
![IMG_1764](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/77725d56-9a02-495f-981d-81dce196871c)

Nothing happens (drop folder). 
![IMG_1767](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/6a720c09-f399-40a1-ae89-e8ddebec3ab3)

Nothing happens (drop file). 
![IMG_1768](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/600b0a08-399b-4cd4-b808-762bb18c6991)

**Comment by timothycarambat** [comment] 2024-05-12 03:16
When you click on the file uploader, you can only select files. _this is intentional and expected_
Dragging and dropping files/folders does appear to work and I am unable to reproduce this bug at this time.

**Comment by atljoseph** [comment] 2024-05-12 03:22
Yeah it’s not working here on the drag drop. Just using Firefox and
whatever the ubuntu stock file app is.

Also the git repo feature doesn’t fetch files from sub folders.

**Comment by atljoseph** [comment] 2024-05-12 05:46
If it is possible to drag drop folders (it’s still not for me…), then what is the purpose of blocking that action when selecting files? Seems a little inconsistent. 

One BIG thing that is missing is the ability to bulk remove vector embeddings. Like, if you change your embedder, you have to swap things out. It isn’t automatically done, which is fine. But, really asking somebody to click this little undo icon 869 times to get rid of 869 files? That’s asking a lot of people.

**Comment by frost19k** [comment] 2024-05-12 05:50
@atljoseph There a button to reset the database in the workspace settings

**Comment by atljoseph** [comment] 2024-05-12 05:55
Yeah but still a pain point when you have to swap out embeddings en masse,
but maybe not all of them.

I’d really like to see a way to have data sources that could have documents
or URL’s attached, and then you could refresh those by re-embedding them.
It’s like a reusable Refreshable thing instead of a one shot.

Right now it’s kind of in between those two and feels a bit clunky. Don’t
get me wrong. It works after things are embedded, and can still get value
from it. That’s more than can be said about Lang Chain.

**Comment by atljoseph** [comment] 2024-05-12 06:28
Like for a confluence page. That’s cool to do. But that confluence page is
gonna change over time. Need an easier way to keep embeddings up to date.

**Comment by amirasyraf** [comment] 2024-05-14 07:23
Dragging folder does not seem to work reliably. I'm getting "File does not exist in upload directory.". I'm not sure what exactly it means by "not exist" here. The files are there. Is it failing to upload into its own directory?

In this instance, the folder I'm uploading contains several files and multiple levels of subfolders.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/15522007/0937f7b6-6e7f-42ea-9ef7-255dfc8c192e)

**Comment by JKDevz** [comment] 2024-05-14 08:47
I am experiencing the same issue as @atljoseph, but I am not using Docker, just the LMStudio and AnythingLLM implementation.

**Comment by computersrmyfriends** [comment] 2024-05-23 20:07
I am not dragging and dropping. I am just selecting a single pdf file and it shows the same error for me

**Comment by computersrmyfriends** [comment] 2024-05-23 20:16
![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/cd43f4cc-eafa-4755-8593-c33010b4d741)

Changed to a different PC with AVX2 support and I'm still struggling to get it up and running perfectly.

I am unable to upload files.

**Comment by Aliman00** [comment] 2024-06-26 19:21
I'm having trouble when dragging and dropping files or folder, then I can just see a spinner with a timer but nothing is happening, even if it's very small file. Clicking on the box and then selecting file works, but drag and drop doesnt.

**Comment by azabraao** [comment] 2024-07-30 00:45
This issue seems to be fixed now. I was able to grab a folder with dozens of subfolders and files and drop it in the app.

**Comment by JKDevz** [comment] 2024-07-31 04:52
That's awesome!

I'll was just thinking of giving mine another go again.

Will confirm the results later.
________________________________

**Comment by JKDevz** [comment] 2024-07-31 09:33
Hrmm, it's not working for me.

I am attempting to load documents on my local network from the File Explorer, perhaps that is the cause?

Might be a firewall issue of sorts, although I am not very familiar with how that all works.

**Comment by timothycarambat** [comment] 2024-07-31 16:43
You have to drag and drop, not click 👍

**Closed by timothycarambat** 2024-07-31 16:43 UTC
Labels: possible bug, needs info / can't replicate
