### ISSUE TITLE
[BUG]: Prisma error

### ISSUE THREAD

**Issue by gaurish-mehra** [Mintplex-Labs/anything-llm#885] opened 2024-03-11 14:55 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

i am using the anythingllm appimage. 
os : arhclinux 
log : 
Error: Invalid `prisma.workspaces.create()` invocation: Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.1.x". This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "debian-openssl-1.1.x". Add "debian-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it: generator client { provider = "prisma-client-js" binaryTargets = ["native", "debian-openssl-1.1.x"] } The following locations have been searched: /tmp/.mount_AnythidhJDAh/resources/backend/node_modules/.prisma/client /tmp/.mount_AnythidhJDAh/resources/backend/node_modules/@prisma/client /home/tim/Documents/anything-llm-desktop/anything-llm/server/node_modules/@prisma/client /tmp/prisma-engines /tmp/.mount_AnythidhJDAh/resources/backend/prisma

**Comment by gaurish-mehra** [comment] 2024-03-11 15:24
okay i found a work around 
first i extracted the appimage file to a folder, then i changed the contents of the file as mentioned in the logs, then i recompile the appimage, and it is now working....

**Comment by shatfield4** [comment] 2024-03-11 17:37
Great thanks for the explanation of the workaround! Closing since the issue is resolved.

**Closed by shatfield4** 2024-03-11 17:37 UTC
Labels: possible bug

**Comment by F-U-B-AR** [comment] 2024-09-08 19:57
I'm having the same issue with the exact same text - but I cant for the life of me work out how to fix it. 

When I open the **schema.prisma** file I cant find any reference to "`binaryTargets" or even debian for that matter. 

any help would be appreciated.
