### ISSUE TITLE
[BUG]: RAG showing all contexts with windows 11 but not windows 10 

### ISSUE THREAD

**Issue by FBTCAD** [Mintplex-Labs/anything-llm#1330] opened 2024-05-10 05:45 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When running RAG for a pdf document in windows 11 all the contexts are shown before answering the prompt but not in windows 10 

<|start_header_id|>system<|end_header_id|>

Given the following conversation, relevant context, and a follow up question, reply with an answer to the current question the user is asking. Return only your response to the question given the above information following the users instructions as needed. Context: [CONTEXT 0]: been consistently providing support to Chinese semiconductorR&Dby establishing research centers and transferring sensitive technologies (Shihua & Costaglione,2023). Lastly, due to the implementation of the October 7 Export Control Regulations, many Amer- ican companies have been forbidden from doing business with their Chinese customers. This situation created a void in the market that will be filled over time by other companies, either from South Korea, Japan, or Europe. This may ultimately strike back and result in a diminution of the American position in the global semiconductor market. 75Chapter 5 Future Advancement Capacity of the Semiconductor Industry in China This chapter serves as a summary of the research and analyses conducted in the preceding parts of the thesis. It aims to evaluate the level of readiness of individual segments within the Chinese semiconductor industry to compete with their direct Western counterparts. The first section is solely devoted to the evaluation and temporal quantification of the tech- nological gap in various segments of the supply chain, beginning with theICdesign stage and concluding with the assembly and testing process. The subsequent section identifies three po- tential scenarios for the advancement of the chip-making industry, wherein the availability of advanced lithography has been used as a variable. 5.1. Progress Towards a Point of Parity with Semiconductor In- dustry Leaders This section examines the position of the various segments within the Chinese chip-making industry in relation to the global technological status. The following paragraphs provide a brief overview of the major advances and key existing challenges. Ultimately, the section reviews the progress, potential deviations from the mainstream, and evaluates the magnitude of the gap between China and specific members of the semiconductor Western world alliance. As the analysis is solely based on publicly available data, assumptions derived from expe- [END CONTEXT 0]

[CONTEXT 1]: ical Capabilities and Recent Advancements Until the beginning of the 21 st century, the Chinese semiconductor industry did not have a strong global position. For years, China has been perceived as a country o�ering a cheap workforce, overwhelmed by its pervasive bureaucracy, and where intellectual property rights have never been a�orded serious legal consideration. The Chinese semiconductor industry was also, for a long time, limited to the production of discrete electronic components. However, due to the strong support of the state, manifested in preferential fiscal policies, high investments in R&Dand infrastructure and support for young talents, China has made tremendous progress in multiple disciplines across the entire semiconductor value chain. The plot shown in Figure21could be a good representation of the above words (SIA, 2022a). It demonstrates the remarkable progress made by Chinese semiconductor companies across the entire value chain. It is interesting to mention that significant growth has been ob- served in all three distinct sectors: fabless, foundry, andOSAT. Table7provides a summary of the annual growth rate of Chinese enterprises as of 2022, categorized by the respective segments. Table 7: Summary of the annual growth rate factors for various segments of the Chinese semiconductor industry (SIA,2022a). Industry segment Annual growth rate Fabless36% Foundry32% OSAT23% 43International Executive MBA HSGMicha≥Bochenek Figure 21: Revenues for 2020 reported by the top 10 Chinese semiconductor enterprises, along with their annual growth rate (SIA,2022b). Figure22shows the impressive 3.5-fold semiconductor market growth in China between 2015 and 2022. It should be noted that until 2015, the main revenue contribution in the Chinese semi- conductor industry was dominated by labor-intensive assembly, packaging and test outsourced services. The year 2016 marked the beginning of a shift towards a knowledge-intensive fabless business model. [END CONTEXT 1]

[CONTEXT 2]: semiconductor devices domestically. The concepts of central planning and the planned economy have always been initiatives distinctive to socialistic states. This strategic social and economic planning in China has been done throughout development initiatives, such as short five-year plans (FYPs) and medium- to long-term plans (MLPs) issued by theCCP. The guidelines regarding the enhancement of the semiconductor sector have been outlined in the following collection of documents that have been published in recent years: –Outline for Advancing the National Integrated Circuit Industry, from June 2014 (PRC State Council,2014); –Notice of the State Council on the Publication of “Made in China 2025”, from May 2015 (PRC State Council, 2015/2022); –Roadmap of Major Technical Domains for Made in China 2025, from September 2015 (PRC State Council, 2015/2020a); –State Council Notice on the Publication of the National 13 th Five-Year Plan for Science and Technology Innovation, from July 2016 (PRC State Council, 2016/2020c); –State Council Notice on the Publication of Certain Policies to Promote the High-Quality Development of the Integrated Circuit Industry and the Software Industry in the New Period, from August 2020 (PRC State Council, 2020/2020b); and –Outline of the People’s Republic of China 14 th Five-Year Plan for National Economic and Social Development and Long-Range Objectives for 2035, from March 2021 (PRC State Council, 2021/2021). Issued in June 2014, the“Outline for Advancing the National Integrated Circuit Industry”is devoted to integrated circuits and their meaning to the Chinese industry and economy. The evidence can for that can be found already in the first sentence of the document: The integrated circuit industry is the core of the information technology industry and is a strategic, basic and leading industry supporting economic and social development and safeguarding national security. (PRC State Council,2014, Introduction) [END CONTEXT 2]

developers Si, M. (2023, August 25). Open-source chip platform to cut reliance on proprietary tech.China Daily.https://www.chinadaily.com.cn/a/202308/25/WS64e7e02ba31035260b81e1b9. html SIA. (2016).Beyond boarders: The global semiconductor value chain.https : / / www . semiconductors . org / wp - content / uploads / 2018 / 06 / SIA - Beyond - Borders - Report - FINAL-June-7.pdf 103International Executive MBA HSGMicha≥Bochenek SIA. (2022a, January 10).China’s share of global chip sales now surpasses Taiwan’s, closing in on Europe’s and Japan’s. Semiconductor Industry Association (SIA).https://www. semiconductors.org/chinas-share-of-global-chip-sales-now-surpasses-taiwan-closing-in- on-europe-and-japan/ SIA. (2022b, January 10).Leading semiconductor firms in China in 2022 based on revenue (in billion u.s. dollars)[Graph]. In Statista. Retrieved November 19, 2023, from. Semicon- ductor Industry Association (SIA).https://www.statista.com/statistics/1292269/china- leading-semiconductor-firms-by-revenue/ SIA. (2021, July 13).Taking stock of China’s semiconductor industry. Semiconductor Indus- try Association (SIA).https : / / www . semiconductors . org / taking - stock - of - chinas - semiconductor-industry/ Sicard, E., & Trojman., L. (2022). Introducing 2-nm/20Å nano-sheet FET technology with buried power rails and nano through-silicon-vias in Microwind.https://hal.science/hal- 03902018 Singh, M. (2023).Semiconductors and artificial intelligence(Report No. IF12497). Congressional Research Service (CSR).https://sgp.fas.org/crs/misc/IF12497.pdf SMIC. (2023a).Company information/Overview. Semiconductor Manufacturing International Corporation (SMIC).https://www.smics.com/en/site/company_info SMIC. (2023b).Foundry solutions: Technology - 28nm. Semiconductor Manufacturing Interna- tional Corporation (SMIC).https://www.smics.com/en/site/technology_advanced_Te [END CONTEXT 3]

<|eot_id|><|start_header_id|>user<|end_header_id|>

in the context check for China semiconductor industry<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Based on Contexts 1, 2, and 3, I found information related to the China semiconductor industry:

Context 1:

The “Outline for Advancing the National Integrated Circuit Industry” (2014) mentions that the integrated circuit industry is a strategic, basic, and leading industry supporting economic and social development and safeguarding national security. This indicates the importance of the chip industry in China’s economy and national security.
The document also mentions the need to strengthen the domestic integrated circuit industry and reduce dependence on foreign technology.
Context 2:

The “Made in China 2025” policy (2015) aims to upgrade China’s manufacturing capabilities, including the semiconductor industry. This policy encourages indigenous innovation and self-reliance in key technologies.
The “Roadmap of Major Technical Domains for Made in China 2025” (2015) identifies the development of advanced chip designs, packaging, and testing as a key area of focus.
Context 3:

According to the Semiconductor Industry Association (SIA), China’s share of global chip sales surpassed Taiwan’s in 2022 and is closing in on Europe’s and Japan’s. This indicates China’s growing presence in the global semiconductor market.
The SIA also reported that leading Chinese semiconductor firms, such as SMIC, Huawei, and Alibaba, are among the top players in the industry.
Other key points:

SMIC (Semiconductor Manufacturing International Corporation) is a major Chinese chipmaker, with a focus on 28nm technology.
China has been actively promoting its domestic chip industry through policies and investments. For example, the government has provided funding for research and development in semiconductors, as well as subsidies for companies to invest in the sector.
Overall, the information suggests that China is prioritizing the development of its semiconductor industry, recognizing its strategic importance for economic growth, national security, and technological advancement.

**Comment by timothycarambat** [comment] 2024-05-10 17:23
What kind of model are you using (name & quantization) and how are you running it (LLM provider, LMstudio, etc)

Commonly, this occurs from just the behavior of the model. Not all models are created equal and depending on their training and method (chat vs instruct vs text vs code, etc) they can behave _exactly_ like this.

It is really not something that can be solved within the context of AnythingLLM and is really just how you specific LLM is behaving inside a system like AnythingLLM. Closing for now, but we can continue chatting in this thread as currently this is not a bug as we have seen this before

**Closed by timothycarambat** 2024-05-10 17:23 UTC
Labels: possible bug
