### ISSUE TITLE
[FEAT]: Configuration of AnythingLLM with https

### ISSUE THREAD

**Issue by flefevre** [Mintplex-Labs/anything-llm#1155] opened 2024-04-20 22:21 UTC
### What would you like to see?

I have downloaded AnythingLLM for Windows
Thanks a lot for this installer.

At first step it ask for "AnythingLLM can work with many LLM providers. This will be the service which handles chatting."
I was not able to put httpS://ollama.myowninstllation.com/ 
The secure https was not recognized and it does not load the models.

Do you have an idea on how to do it?
For llm Models but also for Embedding ? or the Vector databases ?

Thanks a lot.

**Comment by timothycarambat** [comment] 2024-04-21 18:37
This is out of scope as an issue for AnythingLLM. I would assert the issue is how you have your Ollama server set up & configured wherever it may be running. All we do in the code is make a fetch request to the documented Ollama endpoints.
https://github.com/Mintplex-Labs/anything-llm/blob/a3b7239d057d1bbb424641760099af96d0065ffb/server/utils/AiProviders/ollama/index.js#L32

So http/https - we have no preference. Either a port is required in that URL or some other configuration/response setup is required where ollama is running.

**Closed by timothycarambat** 2024-04-21 18:37 UTC
Labels: enhancement, feature request

**Comment by flefevre** [comment] 2024-04-21 18:55
Bonjour,

Thanks for your answer.
My ollama setup is well configured, I can reach it through litellm or open
webui or directly by a curl command.

But when I put the https address in anythingllm windows client, it did not
display the different available models.
The behaviour is different in the anythingllm server mode since I put
http://ollama:11434

Perhaps is it due because I use a reverse proxy
https//ollama.mylabo.com/ that linked to https://traefik.mylabo.com
Si anythingllm is not able to retrieve the model list?

I would look again

François

Le dim. 21 avr. 2024, 20:37, Timothy Carambat ***@***.***> a
écrit :
