### ISSUE TITLE
[FEAT]: Request for Support: Add Llama 3 8B/70B option when using the Groq API.

### ISSUE THREAD

**Issue by PteroMaplePT** [Mintplex-Labs/anything-llm#1171] opened 2024-04-22 14:16 UTC
### What would you like to see?

Groq now supports Llama 3 8B/70B, but it cannot be selected when installing AnythingLLM.
Hope it can be supported.

**Comment by shatfield4** [comment] 2024-04-22 16:42
This will be completed soon by this PR.

connect #1142

**Comment by timothycarambat** [comment] 2024-04-22 19:52
marking as duplicate of #1142

**Closed by timothycarambat** 2024-04-22 19:52 UTC
Labels: enhancement, feature request

**Comment by HuemanInstrument** [comment] 2024-04-24 00:52
has this been implemented yet?

**Comment by timothycarambat** [comment] 2024-04-24 05:02
@HuemanInstrument if you are on desktop you need to wait until the next patch version. Issues merged here are live immediately in the main repo (Docker) but have to be manually released for Desktop.
