### ISSUE TITLE
[BUG]:    ubuntu 20      New Workspace  Workspace Name aaaaaaaaaaa Error: Invalid `prisma.workspaces.create()` invocation: Unable to require(`/tmp/.mount_Anythi2L1mFJ/resources/backend/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node`). Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again. Details: libssl.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wilbur61** [Mintplex-Labs/anything-llm#1120] opened 2024-04-17 21:23 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

when tryin to create new workspace:   got this error

New Workspace

Workspace Name
aaaaaaaaaaa
Error: Invalid `prisma.workspaces.create()` invocation: Unable to require(`/tmp/.mount_Anythi2L1mFJ/resources/backend/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node`). Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again. Details: libssl.so.3: cannot open shared object file: No such file or directory

### Are there known steps to reproduce?

in Gui try to create new workspace

**Comment by wilbur61** [comment] 2024-04-17 21:24
not running on docker,   in a ubuntu linux machine

**Comment by timothycarambat** [comment] 2024-04-17 21:38
Duplicate of #1077 - will be resolved on that issue.

**Closed by timothycarambat** 2024-04-17 21:38 UTC
Labels: possible bug
