### ISSUE TITLE
Can not save workspace on fedora 39

### ISSUE THREAD

**Issue by anchikhorov** [Mintplex-Labs/anything-llm#935] opened 2024-03-20 12:03 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Can not save workspace with error: Error: Invalid `prisma.workspaces.create()` invocation: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-1.1.x". This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "rhel-openssl-1.1.x". Add "rhel-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it: generator client { provider = "prisma-client-js" binaryTargets = ["native", "rhel-openssl-1.1.x"] } The following locations have been searched: /tmp/.mount_AnythiNgkgnj/resources/backend/node_modules/.prisma/client /tmp/.mount_AnythiNgkgnj/resources/backend/node_modules/@prisma/client /home/tim/Documents/anything-llm-desktop/anything-llm/server/node_modules/@prisma/client /tmp/prisma-engines /tmp/.mount_AnythiNgkgnj/resources/backend/prisma

### Are there known steps to reproduce?

Install desktop app on fedora 39 and try to start and setup it as usual. The final step with saving workspace will produce the error : Error: Invalid `prisma.workspaces.create()` invocation: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-1.1.x". This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "rhel-openssl-1.1.x". Add "rhel-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it: generator client { provider = "prisma-client-js" binaryTargets = ["native", "rhel-openssl-1.1.x"] } The following locations have been searched: /tmp/.mount_AnythiNgkgnj/resources/backend/node_modules/.prisma/client /tmp/.mount_AnythiNgkgnj/resources/backend/node_modules/@prisma/client /home/tim/Documents/anything-llm-desktop/anything-llm/server/node_modules/@prisma/client /tmp/prisma-engines /tmp/.mount_AnythiNgkgnj/resources/backend/prisma

**Comment by skamansam** [comment] 2024-03-20 16:33
I am also having this issue on Fedora 39.

**Comment by timothycarambat** [comment] 2024-03-20 17:41
Duplicate of #898 - it is a bug in the bundling of the package and will be patched for the desktop app. Fix is in that issue's thread and/or can run Docker image instead

**Closed by timothycarambat** 2024-03-20 17:41 UTC
Labels: possible bug
