### ISSUE TITLE
[BUG]: Error: 1 documents failed to add. fetch failed

### ISSUE THREAD

**Issue by 1oskao21** [Mintplex-Labs/anything-llm#2266] opened 2024-09-11 11:55 UTC
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

My operating system is winserver 2022 and I created the container with docker: docker run -d -p 3002:3001 --cap-add SYS_ADMIN -v "E:\test910\anyllm\testdata:/app/server/storage" -e STORAGE_DIR=/app/server/storage mintplexlabs/anythingllm, you can upload documents, but save and embed have been error. Lancedb vector database no problem, is changed to chroma error.

### Are there known steps to reproduce?

![12d0db2a3da89a882ced506c6f45340](https://github.com/user-attachments/assets/df277b56-5260-4ecb-a8c5-f8ada4fffe1f)
![695f707a952ef21a6b9b50dba28e6b4](https://github.com/user-attachments/assets/4f02e1c5-7407-4586-a17b-cc42db3909fd)
![d72e217411110775192bde1f3f70ea9](https://github.com/user-attachments/assets/97ed69ba-d6d6-44ca-98cc-6820c86e4ae2)

**Comment by timothycarambat** [comment] 2024-09-11 19:09
Your start command is not like the [official command](https://docs.anythingllm.com/installation/self-hosted/local-docker#recommend-way-to-run-dockerized-anythingllm) and is **very likely** the reason for this issue. No `.env` connection and assumes the storage directory is also writable. We have a powershell command you can use that is the same - just fill out with your storage location.


Alternatively:
Likely duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/964#issuecomment-2018508080

The likely reason is during embedding the model to embed cannot be downloaded for its first-time use. The all-miniLM-v6 model downloads from huggingface.co and fails over to our backup s3 bucket. If both fail. -the default embedder will fail resulting in this erroneous error message.

**Closed by timothycarambat** 2024-09-11 19:09 UTC
Labels: possible bug

**Comment by 1oskao21** [comment] 2024-09-14 10:06
Thank you for your reply. This time, I used the official command to create the container and hang it locally. However, it still gives the same error, and the default vector database Lancedb can save and embed, but when the vector database is changed to chroma, save and embed will give an error.
![Uploading 87cae8e406c9054fed5d4b652b218d9.png…]()

**Comment by 1oskao21** [comment] 2024-09-14 10:07
![c139942315c1f5f935535f6a2c05385](https://github.com/user-attachments/assets/c1b86e3c-d767-439c-9b19-d8c5ef502960)
![e7b2ff044a28ee47b6f342c5d67f382](https://github.com/user-attachments/assets/71dea1fd-8a00-47fe-bd48-2b807b121b34)

**Comment by 1oskao21** [comment] 2024-09-14 10:07
![87cae8e406c9054fed5d4b652b218d9](https://github.com/user-attachments/assets/d1fa91b7-73e8-433e-a46f-8f6cf82c632c)
![93e10cce638d7fc66c06ce7b9445186](https://github.com/user-attachments/assets/baa7041b-4480-4760-a7ba-b8d0272468d4)

**Comment by 1oskao21** [comment] 2024-09-14 10:10
> Your start command is not like the [official command](https://docs.anythingllm.com/installation/self-hosted/local-docker#recommend-way-to-run-dockerized-anythingllm) and is **very likely** the reason for this issue. No `.env` connection and assumes the storage directory is also writable. We have a powershell command you can use that is the same - just fill out with your storage location.
> 
> Alternatively: Likely duplicate of [#964 (comment)](https://github.com/Mintplex-Labs/anything-llm/issues/964#issuecomment-2018508080)
> 
> The likely reason is during embedding the model to embed cannot be downloaded for its first-time use. The all-miniLM-v6 model downloads from huggingface.co and fails over to our backup s3 bucket. If both fail. -the default embedder will fail resulting in this erroneous error message.
Thank you for your reply. This time, I used the official command to create the container and hang it locally. However, it still gives the same error, and the default vector database Lancedb can save and embed, but when the vector database is changed to chroma, save and embed will give an error.
![87cae8e406c9054fed5d4b652b218d9](https://github.com/user-attachments/assets/d1c0adce-3ed8-46a2-bb17-295783e3d50f)
![93e10cce638d7fc66c06ce7b9445186](https://github.com/user-attachments/assets/14dc9807-fb0b-4f82-9655-d28205a214ff)
![c139942315c1f5f935535f6a2c05385](https://github.com/user-attachments/assets/3938aac6-670a-4e64-8eef-cd9b83e590eb)
![e7b2ff044a28ee47b6f342c5d67f382](https://github.com/user-attachments/assets/2d698022-32cf-4f22-abe9-fcd4940a2b52)
