### ISSUE TITLE
/v1/workspace/{slug}/update-embeddings not working

### ISSUE THREAD

**Issue by LooproInc** [Mintplex-Labs/anything-llm#352] opened 2023-11-10 06:54 UTC
Hello! I’ve been able to successfully use all other API endpoints except for the embedding API. After a successful file upload to the workspace (visible on the frontend), the embedding continually returns {‘workspace’: None}. Could you please assist in resolving this issue?

**Comment by tlandenberger** [comment] 2023-11-10 13:29
Hi @LooproInc I've looked into the code and was able to reproduce the error. Looks like the return type of _addDocuments_ function in _documents.js_ is wrong when no documents were added.
So changing line 39 in _document.js_ from
`if (additions.length === 0) return;`
to 
`if (additions.length === 0) return {failed: [], embedded: []};`
fixed the issue for me. Could you check if this solves your problem and then we can create a pull request?

**Comment by timothycarambat** [comment] 2023-11-10 22:00
closed by https://github.com/Mintplex-Labs/anything-llm/pull/353

**Closed by timothycarambat** 2023-11-10 22:00 UTC
