### ISSUE TITLE
[FEAT]: Add enable multi-user support to the initial configuration options during deployment, and possibly add it to the API

### ISSUE THREAD

**Issue by ajferrario** [Mintplex-Labs/anything-llm#1868] opened 2024-07-15 06:39 UTC
### What would you like to see?

As an anythingllm administrator attempting to deploy a number of anythingllm environments, I currently need to access each environment manually to turn on multi-user support before I can use the API to configure the needed users for that environment.

I'd like to have a fully-automated and hands-off deployment option, and this is one of the main manual steps blocking me from achieving this.

I will file other issues for a couple other things needed for fully-automated deployments.

**Comment by timothycarambat** [comment] 2024-07-15 16:21
Duplicate of #1870

**Closed by timothycarambat** 2024-07-15 16:21 UTC
Labels: enhancement, feature request
