### ISSUE TITLE
[BUG]: Updating location Prisma binaries for linux builds. [21700:0331/163659.380261:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: 未找到请求的设置 Prisma schema loaded from prisma/schema.prisma Datasource "db": SQLite database "anythingllm.db" at "file:/home/can/.config/anythingllm-desktop/storage/anythingllm.db"  Error: Schema engine error:  Prisma schema loaded from prisma/schema.prisma Error: EROFS: read-only file system, unlink '/tmp/.mount_Anythi2fjdh3/resources/backend/node_modules/.prisma/client/index.js'  [OllamaProcessManager] Ollama will bind on port 36215 when booted.

### ISSUE THREAD

**Issue by iaoxuesheng** [Mintplex-Labs/anything-llm#1024] opened 2024-04-03 03:07 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Updating location Prisma binaries for linux builds.
[21700:0331/163659.380261:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: 未找到请求的设置
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/can/.config/anythingllm-desktop/storage/anythingllm.db"

Error: Schema engine error:

Prisma schema loaded from prisma/schema.prisma
Error:
EROFS: read-only file system, unlink '/tmp/.mount_Anythi2fjdh3/resources/backend/node_modules/.prisma/client/index.js'

[OllamaProcessManager] Ollama will bind on port 36215 when booted.

### Are there known steps to reproduce?

ubuntu system

**Comment by timothycarambat** [comment] 2024-04-03 03:12
Does this stop the app from booting? Please dont open this issue again as a duplicate. Respond in the thread with the requested information so we can debug and determine if this is really a bug

Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/1000

**Closed by timothycarambat** 2024-04-03 03:12 UTC
Labels: possible bug

**Comment by iaoxuesheng** [comment] 2024-04-03 03:17
> 这会阻止应用程序启动吗？请不要再次以重复形式打开此问题。在线程中响应请求的信息，以便我们可以调试并确定这是否真的是一个错误
> 
> #1000 的副本
yes,it stop the app from booting
