### ISSUE TITLE
[BUG]:  chat-widget override my style on website (docker compose fedore 40)

### ISSUE THREAD

**Issue by mice6** [Mintplex-Labs/anything-llm#1796] opened 2024-07-01 09:52 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hello, why does the JS responsible for adding the chat overwrite the bootstrap 5 styles and change the look of the entire page? Can't it be modified? The JS file is in the min version, it's hard to modify it yourself by changing classes. Maybe some prefix?

### Are there known steps to reproduce?

I'm attaching a file, anythingllm-chat-widget.min.js that's all

**Comment by timothycarambat** [comment] 2024-07-01 18:57
Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/919

Does need Tailwind prefixing

**Closed by timothycarambat** 2024-07-01 18:57 UTC
Labels: possible bug
