### ISSUE TITLE
[BUG]: Ollama call failed with status code 500: llama runner process has terminated: signal: segmentation fault It is on a Mac Sillicon

### ISSUE THREAD

**Issue by venturaEffect** [Mintplex-Labs/anything-llm#2259] opened 2024-09-10 18:28 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Even if there is no Ollama selected and it is an imported LLM I get this message when trying to chat:

Ollama call failed with status code 500: llama runner process has terminated: signal: segmentation fault
It is on a Mac Sillicon

Appreciate your time.

### Are there known steps to reproduce?

Just installed fresh on a Mac (Apple Sillicon) the AnythingLLM desktop. Selected the imported LLM with the AnythingLLM provider, the Embedder is also AnythingLLM and LanceDB on the VectorDB.

Also on the settings from the workspace is Workspace Agent LLM Provider: AnythingLLM and the Workspace Agent model is the custom model: llama-3-Instruct-8b-...

**Comment by shatfield4** [comment] 2024-09-10 18:52
When you use the AnythingLLM provider, this actually uses Ollama under the hood to run the models which is why you are getting Ollama errors.

After you set AnythingLLM as the LLM provider, select a model, and press save do you see the model start to download in the top right corner of the app?

**Comment by venturaEffect** [comment] 2024-09-10 18:55
Hi, we are not using Ollama. We are importing one custom model. And after it is installed we click on save. We did that several times and closed and open the app again. But still get this error.

**Comment by venturaEffect** [comment] 2024-09-10 20:31
When loading a model from Ollama that are by default on AnythingLLM it seems to work but the problem is by trying the custom model. This is strange because the same model on my Windows11 with AnythingLLM desktop also installed works just fine. But on the Apple M1 not.

Do you know why this could be?

Appreciate.

**Comment by timothycarambat** [comment] 2024-09-10 21:14
to clarify: What @shatfield4 is saying is that the _default LLM provider_ inside of AnythingLLM is Ollama. So when you import the model into AnythingLLM and run it, it is using the pre-packaged Ollama inside of AnythingLLM.

The model being used is simply GGUF correct? For the model to work on Windows but not on Mac would indicate to me initially that something went wrong with the file transfer/download ending up with a corrupted or incomplete file. Since GGUF is a portable format, it should work fine across OS as the ollama version in all desktop instances are consistent.

Closing as unable to reproduce for now, but keep the thread open to continue discussion. Are there any [debug logs](https://docs.anythingllm.com/debug) you can pull at the time of crash?

**Closed by timothycarambat** 2024-09-10 21:14 UTC
Labels: possible bug

**Comment by venturaEffect** [comment] 2024-09-10 21:22
Ok, I'm going to download the .gguf file from HuggingFace and import it again to AnythingLLM.

Thanks for the advice.

**Comment by timothycarambat** [comment] 2024-09-10 21:26
Can you link the repo to the model you wish to use? Will help reproduce if it is public
