### ISSUE TITLE
[Feat]: Select all shortcut in document picker.

### ISSUE THREAD

**Issue by pleabargain** [Mintplex-Labs/anything-llm#2332] opened 2024-09-20 07:21 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

v.1.67

![image](https://github.com/user-attachments/assets/0bef8a35-02a7-4624-b013-c319a65166d9)

### Are there known steps to reproduce?

nav to file management
![image](https://github.com/user-attachments/assets/48751db6-8d63-46d7-b6ae-aa62b41c533f)

right click on file in right box
select ALL
the WHOLE UI is selected
![image](https://github.com/user-attachments/assets/2d7d8658-c92b-46fb-a634-0486b2835a2a)

**Comment by timothycarambat** [comment] 2024-09-20 21:25
Select all via the _context menu_ will do what a context menu does for most interfaces (highlights all text). It is not intended to be highjacked to select all file elements in the UI. Marking as not a bug but will edit the issue to instead be a feature request because it would be nice regardless

**Closed** 2024-09-23 19:19 UTC
Labels: enhancement, UI/UX, feature request
