### ISSUE TITLE
[BUG]: Lose Workspaces when I restart AnythingLLM

### ISSUE THREAD

**Issue by dyioulos** [Mintplex-Labs/anything-llm#1562] opened 2024-05-29 19:00 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

After I shut down AnythingLLM, then start it, the workspaces I've created disappear. After I reinstall the application, and start it, the Workspaces appear again.

OS: Windows 11 Pro
AnythingLLM version: latest

**Comment by timothycarambat** [comment] 2024-05-30 01:00
Closing as unable to replicate at this time. If this was an issue for all windows users this would be an issue we would have known very quickly. Is it possible you have two applications of AnythingLLM running? We have no updated the app from 1.5.5 for about two weeks, so the issue is certainly client side and localized to your machine and/or use of the app

**Closed by timothycarambat** 2024-05-30 01:00 UTC
Labels: possible bug, needs info / can't replicate, investigating
