### ISSUE TITLE
[BUG]: Failed to embed the content of a PDF

### ISSUE THREAD

**Issue by GXY2017** [Mintplex-Labs/anything-llm#819] opened 2024-02-27 04:14 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Failed to embed the content of a PDF into a vector model successfully. The PDF has complicated diagrams, 66 pages, and is in Traditional Chinese.  I'm using open AI text-embedding-3-large. 

[20230921174002411910904756_tc.pdf](https://github.com/Mintplex-Labs/anything-llm/files/14414212/20230921174002411910904756_tc.pdf)

When I query the audit,  Chat model cannot find the name.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/29757319/5b6b44b1-5022-4756-bfb6-4fde869e6466)

### Are there known steps to reproduce?

You can upload the same PDF and ask the same question. 
The correct answer is 上會栢誠會計師事務所有限公司 or chatbot may translate into "Shang Hui Bo Cheng Accounting Firm Limited"

**Comment by Vicky4AI** [comment] 2024-02-27 06:28
I got the same problem, it displayed "fetching is failed " during the pdf uploading and embedding process.

**Comment by timothycarambat** [comment] 2024-02-27 17:14
Fetch failure would be related to the vector database if you are using the non-native one. Are you using an external vector database?

**Comment by Vicky4AI** [comment] 2024-02-28 05:39
> Fetch failure would be related to the vector database if you are using the non-native one. Are you using an external vector database?

Hi, thanks for the reply, I am using the LanceDB. The fetch failure shouldn't related to the LLM model, right? is there any other open source vector database recommended :)

**Comment by timothycarambat** [comment] 2024-02-28 07:18
@Vicky4AI If on desktop the `fetch failure` is likely coming from the embedding model, not the LLM or vector DB!
See this comment:
https://github.com/Mintplex-Labs/anything-llm/issues/821

For windows you will want to go to `C:\Users\<USER>\AppData\Roaming\anythingllm-desktop\storage`

**Comment by timothycarambat** [comment] 2024-02-28 07:18
Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/821
(see that issue on how to fix)

**Closed by timothycarambat** 2024-02-28 07:18 UTC
Labels: duplicate
