### ISSUE TITLE
[BUG]: Screen goes white when prompting on a mobile phone 

### ISSUE THREAD

**Issue by wallartup** [Mintplex-Labs/anything-llm#861] opened 2024-03-05 11:46 UTC
### How are you running AnythingLLM?

Docker (local)

### What happened?

![signal-2024-03-05-115505_002](https://github.com/Mintplex-Labs/anything-llm/assets/162115977/be144c42-21de-4fe8-b3d7-34796461247a)

See the image, the white area appears when you write a message and you have to scroll with the finger to remove it. Don't mind the anwer, I was prompting in a different language than english.

How I expect it to behave is that the background should be grey and autoscroll with the text

### Are there known steps to reproduce?

Use the deploy from a mobile phone.

**Comment by shatfield4** [comment] 2024-03-07 00:42
I cannot reproduce this UI bug. Closing for now unless there is a specific message you sent that causes this to happen then please let me know and we can look into again.

**Comment by timothycarambat** [comment] 2024-03-18 16:38
Closing as stale as no other feedback items have come through as replicable. May be client related, but closing as stale currently

**Closed by timothycarambat** 2024-03-18 16:38 UTC
Labels: bug
