### ISSUE TITLE
[FEAT]:  anything llm to be able to run on fedora

### ISSUE THREAD

**Issue by Mobinake** [Mintplex-Labs/anything-llm#1666] opened 2024-06-12 22:36 UTC
### What would you like to see?

I'm trying to run the program on fedora, but I get the error that Prisma Client is based on debian-openssl.

Error: Invalid `prisma.workspaces.create()` invocation: Prisma Client could not locate the Query Engine for runtime “rhel-openssl-3.0.x”. This happened because Prisma Client was generated for “debian-openssl-3.0.x”, but the actual deployment required “rhel-openssl-3.0.x”. Add “rhel-openssl-3.0.x” to `binaryTargets` in the “schema.prisma” file and run `prisma generate` after saving it: generator client { provider = "prisma-client-js” binaryTargets = ["native”, “rhel-openssl-3.0.x”]}

**Comment by timothycarambat** [comment] 2024-06-13 00:23
Duplicate of #898

**Closed** 2024-06-13 00:32 UTC
Labels: enhancement, feature request
