### ISSUE TITLE
[BUG]: Unable to create a Workspace on Manjaro

### ISSUE THREAD

**Issue by kollia** [Mintplex-Labs/anything-llm#1216] opened 2024-04-28 17:39 UTC
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I want to create a Workspace, but I get follow Error message:
'Error: Invalid `prisma.workspaces.create()` invocation: Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.1.x". This happened because Prisma Client was generated for "de
... bian-openssl-3.0.x", but the actual deployment required "debian-openssl-1.1.x". Add "debian-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it: generator client { provider = "prism
... a-client-js" binaryTargets = ["native", "debian-openssl-1.1.x"] } The following locations have been searched: /tmp/.mount_AnythilKOEci/resources/backend/node_modules/.prisma/client /tmp/.mount_AnythilKOEci/resources/backend/node_modu
... les/@prisma/client /home/tim/Documents/anything-llm-desktop/anything-llm/server/node_modules/@prisma/client /tmp/prisma-engines /tmp/.mount_AnythilKOEci/resources/backend/prisma'

I run the model llama3:8B if that helpfull
ollama works on command line after I set by my self the VERSION_ID I gave them the Release version

but I have no debian-openssl
I use Manjaro

my system from lsb_release:
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        23.1.4
Codename:       Vulcan

my openssl version
OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)

the installed packages are
core/libssh2 1.11.0-1 (236.2 KiB 462.1 KiB) (Installiert)
    A library implementing the SSH2 protocol as defined by Internet Drafts
core/openssh 9.6p1-3 (1.1 MiB 5.5 MiB) (Installiert)
    SSH protocol implementation for remote login, command execution and file transfer

### Are there known steps to reproduce?

Every time I want to create any new Workspace

**Comment by timothycarambat** [comment] 2024-04-28 20:29
Duplicate of https://github.com/Mintplex-Labs/anything-llm/issues/898!

This is a known issue for desktop clients but we do not have access to a running non-ubuntu desktop client we can debug with, so it's been really frustrating to say the least. Seems like no matter how we have attempted to solve this someone comes along and says it doesn't work and are on some other other other version of Linux.

Current workaround for Linux AppImage: https://github.com/Mintplex-Labs/anything-llm/issues/1077#issuecomment-2062921781

**Closed by timothycarambat** 2024-04-28 20:29 UTC
Labels: possible bug
